name: campus_app
description: Mobile application for university

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.8+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^6.0.1
  hive: ^2.0.4
  graphql_flutter: ^5.0.0
  url_launcher: ^6.0.12
  shared_preferences: ^2.0.8
  intl: ^0.17.0
  font_awesome_flutter: ^9.0.0
  image_picker: ^0.8.4+2
  connectivity: ^3.0.3
  flutter_email_sender: ^5.0.0
  carousel_slider: ^4.0.0
  photo_view: ^0.12.0
  google_maps_flutter: ^2.0.6
  http: ^0.13.3
  cached_network_image: ^3.1.0




dev_dependencies:
  flutter_native_splash: ^1.1.8+4


flutter_native_splash:
  color: "#E1F3FF"
  image: assets/icons/campusAppIcon.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/IconCampusApp.png"
  adaptive_icon_background: "#E1F3FF"
  android_gravity: fill
  ios_content_mode: scaleAspectFill


  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/images/
    - assets/translations/
    - assets/icons/

  fonts:
    - family: ArialRounded
      fonts:
        - asset: assets/fonts/ARLRDBD.ttf


  uses-material-design: true
